Client/Models/ErrorViewModel.cs
using System;

namespace Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Models/HomePageModel.cs
using API.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Models
{
    public class HomePageModel
    {
        public List<Post> Posts { get; set; }
        public List<Category> Categories { get; set; }
    }
}

Client/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using API.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;

namespace Client.Controllers
{
    public class CategoryController : Controller
    {
        string Baseurl = "https://localhost:44305";

        // GET: CategoryController
        public ActionResult Index()
        {
            return View();
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: CategoryController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            Category category = new Category();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("/api/categories/" + id);
                if (Res.IsSuccessStatusCode)
                {
                    var categoryResponse = Res.Content.ReadAsStringAsync().Result;
                    if (categoryResponse != "")
                        category = JsonConvert.DeserializeObject<Category>(categoryResponse);

                    return View(category);
                }

            }
            return View(category);

        }
    }
}

Client/Controllers/HomeController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

using System.Threading.Tasks;
using API.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        string Baseurl = "https://localhost:44305";

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {

            HomePageModel homeData = new HomePageModel();


            homeData.Categories = await GetCategoriesAsync();
            homeData.Posts = await GetPostsAsync();
            //returning the employee list to view
            return View(homeData);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }      


        public async Task<List<Category>> GetCategoriesAsync()
        {
            List<Category> Categories = new List<Category>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("/api/categories");
                if (Res.IsSuccessStatusCode)
                {
                    var categoryResponse = Res.Content.ReadAsStringAsync().Result;
                    if(categoryResponse != "")
                        Categories = JsonConvert.DeserializeObject<List<Category>>(categoryResponse);   

                    return Categories;
                }

            }
            return Categories;

        }


        public async Task<List<Post>> GetPostsAsync()
        {
            List<Post> Posts = new List<Post>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("/api/posts");
                if (Res.IsSuccessStatusCode)
                {
                    var postResponse = Res.Content.ReadAsStringAsync().Result;
                    if (postResponse != "")
                        Posts = JsonConvert.DeserializeObject<List<Post>>(postResponse);

                    return Posts;
                }

            }
            return Posts;

        }
    }
}

Client/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using API.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;

namespace Client.Controllers
{
    public class PostController : Controller
    {

        string Baseurl = "https://localhost:44305";

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }


        // GET: CategoryController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {

            Post post = new Post();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("/api/posts/" + id);
                if (Res.IsSuccessStatusCode)
                {
                    var postResponse = Res.Content.ReadAsStringAsync().Result;
                    if (postResponse != "")
                        post = JsonConvert.DeserializeObject<Post>(postResponse);

                    return View(post);
                }

            }
            return View(post);

        }

    }
}

Client/Views/Category/Create.cshtml
<div class="card col-10 col-lg-6  mt-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title">Add Category</h5>


        <div class="form-group row">
            <label for="categoryTitle" class="col-sm-3 col-form-label">Title</label>
            <div class="col-sm-7">
                <input type="text" name="title" class="form-control" id="categoryTitle" placeholder="Category title">
                <div id="categoryError" class="invalid-feedback">
                    This category already exists
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <button class="btn btn-primary" id="saveCategoryButton">Save</button>
            </div>
        </div>
    </div>
</div>



<script type="module" src="~/js/Category.js"></script>

Client/Views/Category/Edit.cshtml
@model API.Models.Category




<div class="card col-10 col-lg-6  mt-5 mx-auto" >
    <div class="card-body">
        <h5 class="card-title">Edit Category</h5>


        <div class="form-group row">
            <label for="categoryTitle" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-7">
                <input type="text" name="title" class="form-control" id="categoryTitle" data-id="@Model.Id" placeholder="Category title" value="@Model.Title">
                <div id="categoryError" class="invalid-feedback">
                    This category already exists
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <button class="btn btn-primary" id="editCategoryButton">Save</button>
            </div>
        </div>
    </div>
</div>



<script type="module" src="~/js/Category.js"></script>

Client/Views/Home/Index.cshtml
@model Client.Models.HomePageModel
@{
    ViewData["Title"] = "Home Page";
}


<div class="col-10 col-lg-6  mt-5 mx-auto p-5">
    @{
        <div class="row  mb-2">
            <h1 class="col-12 col-lg-7">Categories:</h1>
            <div class="col-12 col-lg-3  d-flex justify-content-lg-start text-left">
                <a href="/category/create" class="btn btn-outline-primary my-auto"> Add </a>
            </div>

            <div id="categoryError" class="col-12 col-lg-7 invalid-feedback">
                This post already exists
            </div>
        </div>
        foreach (var category in Model.Categories)
        {
            <div class="d-block my-1">
                <a href="#" class="btn btn-outline-danger px-2 py-0 border-danger removeCategoryButton" data-id="@category.Id">X</a>
                <a href="@Url.Action("Edit", "Category", new { id = category.Id})">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                    </svg>
                    @category.Title
                </a>
            </div>
        }

        <div class="row mt-5 mb-2">
            <h1 class="col-12 col-lg-7">Posts:</h1>
            <div class="col-12 col-lg-3  d-flex justify-content-lg-start text-left">
                <a href="/post/create" class="btn btn-outline-primary my-auto"> Add </a>
            </div>
        </div>
        foreach (var post in Model.Posts)
        {
            <div class="d-block my-1">
                <a href="#" class="btn btn-outline-danger px-2 py-0 border-danger removePostButton" data-id="@post.Id">X</a>
                <a href="@Url.Action("Edit", "Post", new { id = post.Id})">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                    </svg>
                    @post.Title

                </a>
            </div>
        }
    }
</div>

<script type="module" src="~/js/Category.js"></script>
<script type="module" src="~/js/Post.js"></script>

Client/Views/Post/Create.cshtml
<div class="card col-10 col-lg-6  mt-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title">Add Post</h5>


        <div class="form-group row">
            <label for="postTitle" class="col-sm-3 col-form-label">Title</label>
            <div class="col-sm-7">
                <input type="text" name="title" class="form-control" id="postTitle" placeholder="Post title">
                <div id="postError" class="invalid-feedback">
                    This post already exists
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="dropdownPost" class="col-sm-3 col-form-label">Category</label>
            <div class="col-sm-7">

                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownCategory" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Post
                    </a>
                    <div class="d-inline justify-content-center text-center" id="createCategoryButton">
                        <a href="/category/create" class="btn btn-outline-primary my-auto"> Add </a>
                    </div>
                    <div id="postDropdownError" class="invalid-feedback">
                        This post already exists
                    </div>
                    <div class="dropdown-menu" id="dropdownCategoryList" aria-labelledby="dropdownMenuLink">
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group row">
            <label for="postPubDate" class="col-sm-3 col-form-label">Pub Date</label>
            <div class="col-sm-7">
                <input type="date" id="postPubDate" name="trip-start"
                       value="2022-03-28">
            </div>
        </div>


        <div class="form-group">
            <label for="postContent">Content</label>
            <textarea class="form-control" id="postContent" rows="3"></textarea>
            <div id="postContentError" class="invalid-feedback">
                The content field cannot be empty!
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button class="btn btn-primary" id="savePostButton">Save</button>
            </div>
        </div>
    </div>
</div>



<script type="module" src="~/js/Post.js"></script>


<style>
    textarea {
        resize: none;
    }
</style>

Client/Views/Post/Edit.cshtml
@model API.Models.Post




<div class="card  col-10 col-lg-6 mt-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title">Add Post</h5>


        <div class="form-group row">
            <label for="postTitle" class="col-sm-3 col-form-label">Title</label>
            <div class="col-sm-7">
                <input type="text" name="title" class="form-control" id="postTitle" data-id="@Model.Id" placeholder="Post title" value="@Model.Title">
                <div id="postError" class="invalid-feedback">
                    This post already exists
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="dropdownPost" class="col-sm-3 col-form-label">Category</label>
            <div class="col-sm-7">

                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownCategory" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Post
                    </a>
                    <div class="d-inline justify-content-center text-center" id="createCategoryButton">
                        <a href="/category/create" class="btn btn-outline-primary my-auto"> Add </a>
                    </div>
                    <div id="postDropdownError" class="invalid-feedback">
                        This post already exists
                    </div>
                    <div class="dropdown-menu" id="dropdownCategoryList" data-selectedCategory="@Model.Category.Id" aria-labelledby="dropdownMenuLink">
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group row">
            <label for="postPubDate" class="col-sm-3 col-form-label">Pub Date</label>
            <div class="col-sm-7">
                <input type="date" id="postPubDate" name="trip-start"
                       value="@Model.PublicationDate.ToString("yyyy-MM-dd")">
            </div>
        </div>

        <div class="form-group">
            <label for="postContent">Content</label>
            <textarea class="form-control" id="postContent" rows="3">@Model.Content</textarea>
            <div id="postContentError" class="invalid-feedback">
                The content field cannot be empty!
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button class="btn btn-primary" id="editPostButton">Save</button>
            </div>
        </div>
    </div>
</div>



<script type="module" src="~/js/Post.js"></script>


<style>
    textarea {
        resize: none;
    }
</style>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog Engine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog Engine</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>